### ISSUE TITLE
Compilation error (CUDA, Linux), possibly XMR-STAK_THREADS

### ISSUE THREAD

**Issue by ondrejtichacek** [fireice-uk/xmr-stak#191]
Trying to compile on Ubuntu 16.04, GTX 760, with the following options, I get an error (below). When I compile without setting `-DXMR-STAK_THREADS=32`, the compilation is successful and I get 320 H/s, using 64 threads, and 12 Blocks. Don't know, whether this is ok or not (first time user).

Compile options:
```
  -DMICROHTTPD_ENABLE=OFF
  -DMHTD=/usr/include/microhttpd.h
  -OpenSSL_ENABLE=ON
  -DXMR-STAK_CURRENCY=monero
  -DCPU_ENABLE=OFF
  -DHWLOC_ENABLE=OFF
  -DOpenCL_ENABLE=OFF
  -DCUDA_ENABLE=ON
  -DCUDA_ARCH=30
  -DXMR-STAK_LARGEGRID=OFF
  -DXMR-STAK_THREADS=32
```
Error:
```
[ 83%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o
/home/ondrej/repo/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(171): error: attributes are not allowed here

1 error detected in the compilation of "/tmp/tmpxft_0000514d_00000000-7_cuda_core.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.o.cmake:266 (message):
  Error generating file
  /home/ondrej/repo/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_core.cu.o


CMakeFiles/xmrstak_cuda_backend.dir/build.make:63: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by psychocrypt** [comment]
Thanks for reporting: Please repeat `-DXMR-STAK_THREADS=32
` until the bug is fixed

**Comment by psychocrypt** [comment]
fixed with #221
