### ISSUE TITLE
Error in make install

### ISSUE THREAD

**Issue by mrddter** [fireice-uk/xmr-stak#647]
hi, i got this on make install on ubuntu 17.10
(gcc (Ubuntu 5.5.0-1ubuntu1) 5.4.1 20171010)

[ 28%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from /home/dev/xmr-stak/xmrstak/version.cpp:1:0:
/home/dev/xmr-stak/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
/home/dev/xmr-stak/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 100
^
CMakeFiles/xmr-stak-backend.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o' failed
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Elycin** [comment]
For Ubuntu 17.10, you have an old version of GCC.
looking at my local development machine you should be atleast running GCC 7.2.0 (7.2.0-8ubuntu3).

try upgrading and see what happens!

**Comment by swflb** [comment]
I have found the same issue with Ubuntu 17.04. If build with gcc 7.2.x and cuda, the build fails claiming that it can not build with compiler version greater than 5 the compiler complains:
```
In file included from /usr/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
```

 If I then setup gcc 5.4.x and attempt to build the same source (with cuda), I get the exact error as reported by @mrddter.

With gcc 7.2.x, if I disable cuda, then the build succeeds.

**Comment by kayvin42** [comment]
Had the same issue on Ubuntu 17.04, was able to get it working with clang instead:
```
apt-get install clang
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
cmake .. -DCUDA_COMPILER=clang -DOpenCL_ENABLE=OFF
```
