### ISSUE TITLE
xmr-stak: relocation error (Ubuntu) can't get it to mine although GPU & CPU are good (xmr-stak-portbin-linux.tar.gz )

### ISSUE THREAD

**Issue by dlegend116** [fireice-uk/xmr-stak#173]
I am using xmr-stak-portbin-linux.tar.gz complied exactly as the website instructs.

Here is the complete output(Please disregard the AMD platform not found I did not install these cards yet, just the GTX and Ryzen 7 CPU):

[2017-11-20 00:57:18] : Start mining: MONERO
 [2017-11-20 00:57:18] : Starting NVIDIA GPU thread 0, no affinity.
 [2017-11-20 00:57:18] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
 [2017-11-20 00:57:18] : WARNING: backend AMD disabled.
 [2017-11-20 00:57:18] : Starting single thread, affinity: 0.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 2.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 4.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 6.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 8.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 10.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 12.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Starting single thread, affinity: 14.
 [2017-11-20 00:57:18] : hwloc: memory pinned
 [2017-11-20 00:57:18] : Fast-connecting to monerohash.com:3333 pool ...
 /home/danny/Downloads/stak/xmr-stak: "relocation error: /lib/x86_64-linux-gnu/libnss_dns.so.2: symbol __resolv_context_get, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference"

**Comment by dlegend116** [comment]
Should I just compile from scratch as opposed to using the Portbin?

**Comment by psychocrypt** [comment]
Which distribution do you use?
If the portable bin is not working than yes olease compile it from scratch.
The portable bin is an test if we can provide linux binaries.

**Comment by vitorgatti** [comment]
Same issue here

Ubuntu 17.10 x86_64

```
ii  build-essential                               12.4ubuntu1                                 amd64        Informational list of build-essential packages
ii  cmake                                         3.9.1-1                                     amd64        cross-platform, open-source make system
ii  cmake-data                                    3.9.1-1                                     all          CMake data files (modules, templates and documentation)
ii  libhwloc-dev:amd64                            1.11.5-1                                    amd64        Hierarchical view of the machine - static libs and headers
ii  libmicrohttpd-dev                             0.9.55-1                                    amd64        library embedding HTTP server functionality (development)
ii  libssl-dev:amd64                              1.0.2g-1ubuntu13.2                          amd64        Secure Sockets Layer toolkit - development files

```

**Comment by dlegend116** [comment]
@psychocrypt I am using latest Ubuntu 17 x86_64 as @vitorgatti .

@vitorgatti did you manually compile from scratch? Still receiving same error as me using "portbin" shown in OP?

**Comment by vitorgatti** [comment]
no, used the portbin, will compile from scratch now and see if it works

**Comment by vitorgatti** [comment]
```
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:203 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support

```

Downloading `nvidia-cuda-toolkit` and trying again in a few minutes...

**Comment by dlegend116** [comment]
This is all you need please tried I did and it worked to get CUDA going.

1. sudo dpkg -i cuda-repo-ubuntu1704_9.0.176-1_amd64.deb

2. sudo apt-key adv --fetch-keys
http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64/7fa2af80.pub

3.sudo apt-get update

4.sudo apt-get install cuda

**Comment by dlegend116** [comment]
@vitorgatti can you post what you did to compile please?

**Comment by vitorgatti** [comment]
```
ii  libcuda1-387                                  387.22-0ubuntu0~gpu17.10.2                  amd64        NVIDIA CUDA runtime library
ii  libcudart8.0:amd64                            8.0.61-1                                    amd64        NVIDIA CUDA Runtime Library
ii  nvidia-cuda-dev                               8.0.61-1                                    amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                               8.0.61-1                                    all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                               8.0.61-1                                    amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                           8.0.61-1                                    amd64        NVIDIA CUDA development toolkit

```
```
/usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:222 (message):
  Error generating

```

Too much of a hassle to install deb files from outside now, compiled with `-DCUDA_ENABLE=OFF` for now, xmr-stak is working...

**Comment by dlegend116** [comment]
@vitorgatti can you post the steps so that I can try the way you did to also confirm, not strong in linux. That's why I didn't compile if you post what you did it will be help so I can more quickly get up and running

**Comment by vitorgatti** [comment]
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md

```
# Ubuntu / Debian
    sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
    git clone https://github.com/fireice-uk/xmr-stak.git
    mkdir xmr-stak/build
    cd xmr-stak/build
    cmake ..
    make install
```

Change `cmake ..` to `cmake -DCUDA_ENABLE=OFF ..` and you're good to go

**Comment by andrebardo** [comment]
Yes... working only on CPU...

**Comment by vitorgatti** [comment]
tried following the instructions to mine with cuda, but got the same error:

```
In file included from /usr/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:222 (message):
```

is the portbin file pre-compiled with cuda support? maybe that's why it's not working on Ubuntu 17.10?

**Comment by andrebardo** [comment]
I just installed gcc-5 and g++-5, switched to it with update-alternatives configured, and tried basic cmake ..

I got another error:

```
[ 79%] Building CXX object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/minethd.cpp.o
In file included from /home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/minethd.cpp:25:0:
/home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/autoAdjust.hpp: In member function ‘void xmrstak::nvidia::autoAdjust::generateThreadConfig()’:
/home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/autoAdjust.hpp:92:72: error: ‘to_string’ is not a member of ‘std’
  conf += std::string("  // gpu: ") + ctx.name + " architecture: " + std::to_str
```
And a lot of other errors for the same ‘to_string’ issue.

**Comment by vitorgatti** [comment]
it seems that cuda can't compile with gcc 5 or grater

**Comment by andrebardo** [comment]
gcc version 5.4.1 20171010 (Ubuntu 5.5.0-1ubuntu1)

**Comment by andrebardo** [comment]
I changed to clang 3.8 (used export CC and CXX function) and still getting errors...
I used:
```
export CC=/usr/bin/clang-3.8
export CXX=/usr/bin/clang++-3.8
cmake . -DCUDA_COMPILER=clang -DCUDA_ARCH=50
make install
```
and got this:
```
In file included from /home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu:56:
/home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_aes.hpp:303:14: error: use of undeclared identifier 'threadIdx'
        for(int i = threadIdx.x; i < 1024; i += blockDim.x)
                    ^
/home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_aes.hpp:303:42: error: use of undeclared identifier 'blockDim'
        for(int i = threadIdx.x; i < 1024; i += blockDim.x)
                                                ^
/home/kurumin/Monero/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu:70:16: error: use of undeclared identifier '__umul64hi'
        *product_hi = __umul64hi( multiplier, multiplicand );
```
[...] There are a total of 20 errors like these.

**Comment by vitorgatti** [comment]
No news about this? Which Ubuntu version was the portbin compiled?

**Comment by fireice-uk** [comment]
@vitorgatti 16.04 we have removed it since it is a bit too problematic for production environment right noe.

**Comment by fireice-uk** [comment]
I will have a bit more in depth look at it next week and try to resolve it.

**Comment by vitorgatti** [comment]
Thanks a lot :)

If you need help testing/debugging, I can help (Ubuntu 17.10 x86_64 with NVIDIA GPU).

One suggestion though, `xmr-stak` has the `--noCPU` and `--noAMD` options, maybe a `--noNVIDIA` could help to solve some issues (cuda libs errors), including people that only want to mine with their CPU.

**Comment by MarkStudholme** [comment]
Hi all, quite similar issue here. I have a CPU only machine on Ubuntu 16.04 LTS. I enter the following commands:

sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
cmake -DOpenCL_ENABLE=OFF -DCUDA_ENABLE=OFF ..
make install

Everything goes well. But then I am stuck at where to configure the miner and start it. I am currently using XMR-STAK-CPU so I am used to that config. Do I just run: ./xmrstak --noNVIDIA --noAMD
 and in what folder do I run this?

**Comment by DavidBruchmann** [comment]
You wrote the folder already: "./" that's the folder where the binary resides.
You can enter an absolute path instead then you can place it everywhere you like:
i.e. /usr/bin/xmrstak
or ~/xmrstak
where ~ represents the current users home-folder.

**Comment by cipixul** [comment]
Same issue here, ubuntu 17.10, cuda won't compile.
Patiently waiting for a solution :)

**Comment by AaronNBrock** [comment]
Same here, ubunut 17.10 with cuda 8 & I'm getting the "unsupported GNU version! gcc versions later than 5 are not supported" error as well.

**Comment by psychocrypt** [comment]
This is a restriction from cuda8 please use gcc 5.x for the compile

**Comment by cipixul** [comment]
@psychocrypt The version with which I tried it was 4.8 and 5.4.1, right now I have this version:
gcc --version
gcc (Ubuntu 5.5.0-1ubuntu1) 5.4.1 20171010
and still won't compile.
