### ISSUE TITLE
Build issue with 2.4.2 in Windows?

### ISSUE THREAD

**Issue by s4m0k** [fireice-uk/xmr-stak#1331]
Im getting a fatal error building 2.4.2, please note that just 3 days ago I build 2.4.1 with not issues at all.  

The error is this:

`"C:\Mining\temp\xmr-stak-2.4.2\build\install.vcxproj" (defaul
t target) (1) ->
"C:\Mining\temp\xmr-stak-2.4.2\build\ALL_BUILD.vcxproj" (defa
ult target) (3) ->
"C:\Mining\temp\xmr-stak-2.4.2\build\xmrstak_cuda_backend.vcx
proj" (default target) (7) ->
(CustomBuild target) ->
  c:\program files\nvidia gpu computing toolkit\cuda\v9.1\inc
lude\crt/host_config.h(135): fatal error C1189: #error:  -- u
nsupported Microsoft Visual Studio version! Only the versions
 2012, 2013, 2015 and 2017 are supported! [C:\Mining\temp\xmr
-stak-2.4.2\build\xmrstak_cuda_backend.vcxproj]

    1 Warning(s)
    1 Error(s)`

**Comment by Spudz76** [comment]
Have you allowed VS2017 to do updates?
You may need to re-install the older (14.11.25503) compiler, it seems one of the newer updates REMOVES manually installed older versions and is not obvious about it.  No other version (yet) works with CUDA9.1

You may also try applying the latest CUDA9 point releases, they post them on the usual CUDA9 download page.  I think they are on update 3?  That occasionally adds/approves support for newer compilers and may allow you to use VS the way it is configured.

**Comment by ykutlu** [comment]
Please xmr stak Gpu intensive control disable. Your control, worked gpu slowed.
your control not need. Please remove. !!!

**Comment by s4m0k** [comment]
@Spudz76 Thanks for the reply.
 My apologies, was too late already and my eyes were getting tired, I overlooked below steps:

`# Execute next line only if compiling for Cuda 9.1 and using Visual Studio 2017 >= 15.5 (released 12/04/17)
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11  

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"`

I deleted the source, re-extracted from zip, then followed step by step the guide on how to compile in windows

I managed to compile now.


Thanks again!
