### ISSUE TITLE
CryptoNightR code and CUDA 7.5

### ISSUE THREAD

**Issue by Zenitur** [fireice-uk/xmr-stak#2353]
`cuda_extra.cu` and `cuda_code.cu` are compiling perfectly. The error appears when compiling the code for using that.
```
Scanning dependencies of target xmrstak_cuda_backend
[ 77%] Building CXX object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp.o
/home/newel/xmr-stak-master/xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp: In function ‘void xmrstak::nvidia::CryptonightR_build_program(std::vector<char>&, std::string&, const xmrstak_algo&, uint64_t, uint32_t, int, int, std::string)’:
/home/newel/xmr-stak-master/xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp:210:64: error: ‘nvrtcAddNameExpression’ was not declared in this scope
     result = nvrtcAddNameExpression(prog, "CryptonightR_phase2");
                                                                ^
/home/newel/xmr-stak-master/xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp:243:68: error: ‘nvrtcGetLoweredName’ was not declared in this scope
     result = nvrtcGetLoweredName(prog, "CryptonightR_phase2", &name);
                                                                    ^
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [all] Error 2
```
The code:
```
    result = nvrtcAddNameExpression(prog, "CryptonightR_phase2");
    if (result != NVRTC_SUCCESS) {
        printer::inst()->print_msg(L0, "nvrtcAddNameExpression failed: %s", nvrtcGetErrorString(result));
        nvrtcDestroyProgram(&prog);
        return;
    }
```

**Comment by Spudz76** [comment]
I haven't been able to get CUDA 7.5 to work, ever

HOW?

Was literally about to drop support for it, why not 8.0?

**Comment by Spudz76** [comment]
But also, CN-R destroyed any hope for CUDA 7.5
[xmrig-nvidia abandoned it too due to this same error](https://github.com/xmrig/xmrig-nvidia/commit/4ee84fea428b77ee1c47423736c49954733e4d36)

but seriously I never got even 2.5.x to compile on 7.5 so you had been doing better than that haha

**Comment by Zenitur** [comment]
It's easy to make GCC 6 work with CUDA 7.5. Just replace `math_functions.h` file with the CUDA 8.0 version without any changes. Then edit `math_functions.hpp` and move only first half of changes from CUDA 8.0. Finally, edit `host_config.h` to increase maximum GCC version that it can work with. I attach the patch for CUDA 7.5 that making it work with GCC 5 and 6

The reason that I using CUDA 7.5 is that my laptop cannot work with NVIDIA driver 361.xx and newer. So I still using 352.xx. [This is my bug report](https://devtalk.nvidia.com/default/topic/1045412/linux/nvidia-geforce-650m-/post/5304610/). I can insta
[make-cuda-7-5-working-with-gcc-6.patch.tar.gz](https://github.com/fireice-uk/xmr-stak/files/2990086/make-cuda-7-5-working-with-gcc-6.patch.tar.gz)

ll current version of the driver only with `--no-opengl-files` option, and xmr-stak is working perfect with it. But I didn't mine all the time, and sometimes I want to play videogames.

**Comment by Zenitur** [comment]
This is my build of xmr-stak 2.5.2. It contains a lot of CUDA binaries starting from 7.5 ending 10.0. https://yadi.sk/d/S29rvip3Ngrovg

**Comment by Spudz76** [comment]
what gpu is it actually?
I was trying to make this thing do something:
`01:00.0 VGA compatible controller: NVIDIA Corporation G71M [GeForce Go 7950 GTX] (rev a1)`
even 304 legacy is like, what?
seems like even if I did get 7.5 to work it wouldn't

**Comment by Zenitur** [comment]
GeForce 7950 was made in 2005 year. This is OpenGL 2.1.2 and DirectX 9.0c videocard. There is no CUDA support.

I have GeForce 650M. This is Kepler, and it is CUDA 10.0 compatible videocard. I prefer to use 352.xx driver with that because 361.xx and newer are doesn't working in my case. I can install 410.xx with ``--no-opengl-files`` parameter, then use Intel intagrated graphics. But I prefer 352.xx.

The fix is not required. I can use a workaround if it's exist.
