### ISSUE TITLE
Unable to compile on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by chiwalfrm** [fireice-uk/xmr-stak#202]
have met all dependency requirements.
rig has both one 1070 GTX (Nvidia) and three AMD RX 480-8GB.
have installed AMD APP SDK 3.0 (AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64)
have installed Cuda 9.0.

the error is at "make install" command.

```
asus@asus1:~/Downloads$ git clone https://github.com/fireice-uk/xmr-stak.git
Cloning into 'xmr-stak'...
remote: Counting objects: 2652, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 2652 (delta 18), reused 23 (delta 12), pack-reused 2617
Receiving objects: 100% (2652/2652), 808.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1849/1849), done.
Checking connectivity... done.
asus@asus1:~/Downloads/xmr-stak$ mkdir build
asus@asus1:~/Downloads/xmr-stak$ cd build
asus@asus1:~/Downloads/xmr-stak/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.5")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /home/asus/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so (found version "2.0")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/asus/Downloads/xmr-stak/build
asus@asus1:~/Downloads/xmr-stak/build$ make install
Scanning dependencies of target xmr-stak-c
[  2%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 17%] Linking C static library bin/libxmr-stak-c.a
[ 17%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 20%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 29%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 32%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 35%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 38%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 41%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 47%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 58%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 64%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 67%] Linking CXX static library bin/libxmr-stak-backend.a
[ 67%] Built target xmr-stak-backend
[ 70%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o
[ 73%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(184): error: identifier "__builtin_ia32_pf2iw" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(190): error: identifier "__builtin_ia32_pfnacc" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(196): error: identifier "__builtin_ia32_pfpnacc" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(202): error: identifier "__builtin_ia32_pi2fw" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(208): error: identifier "__builtin_ia32_pswapdsf" is undefined

5 errors detected in the compilation of "/home/asus/Downloads/AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64/tmpxft_0000278a_00000000-14_cuda_extra.compute_70.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.cmake:266 (message):
  Error generating file
  /home/asus/Downloads/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


CMakeFiles/xmrstak_cuda_backend.dir/build.make:63: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
asus@asus1:~/Downloads/xmr-stak/build$

```

**Comment by alextrezvy** [comment]
Me also unable to compile on Ubuntu 16.04. The error is: "make[2]: *** No rule to make target '/home/user/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'bin/libxmrstak_opencl_backend.so'.  Stop".

**Comment by psychocrypt** [comment]
> /usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(184): error: identifier
"__builtin_ia32_pf2iw" is undefined

There is something wrong with your system compiler you have a undifined
function in a system header. Thats nothing we can fix. I will try to
reproduce it in a docker container but think thats something wrong with
your installation.

**Comment by chiwalfrm** [comment]
@alextrezvy you can fix that error with:
sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so /usr/lib/libOpenCL.so.1

**Comment by alveeno** [comment]
`alvin@alvin-wc:~/Desktop/xmr-stak/build$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic .
-- Set miner currency to 'monero' and 'aeon'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alvin/Desktop/xmr-stak/build
alvin@alvin-wc:~/Desktop/xmr-stak/build$ make install
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 17%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 24%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 27%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 31%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 34%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 37%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 41%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 48%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 51%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 58%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 62%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 65%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 72%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 75%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 79%] Linking CXX static library bin/libxmr-stak-backend.a
[ 79%] Built target xmr-stak-backend
Scanning dependencies of target xmrstak_opencl_backend
[ 82%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o
/home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp: In function ‘size_t InitOpenCLGpu(cl_context, GpuContext*, const char*)’:
/home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:239:23: warning: ‘_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)’ is deprecated [-Wdeprecated-declarations]
  ctx->CommandQueues = clCreateCommandQueue(opencl_ctx, ctx->DeviceID, CommandQueueProperties, &ret);
                       ^~~~~~~~~~~~~~~~~~~~
In file included from /home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.hpp:8:0,
                 from /home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:51:
/home/alvin/AMDAPPSDK-3.0/include/CL/cl.h:1359:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^~~~~~~~~~~~~~~~~~~~
/home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:239:99: warning: ‘_cl_command_queue* clCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int*)’ is deprecated [-Wdeprecated-declarations]
  clCreateCommandQueue(opencl_ctx, ctx->DeviceID, CommandQueueProperties, &ret);
                                                                              ^
In file included from /home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.hpp:8:0,
                 from /home/alvin/Desktop/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:51:
/home/alvin/AMDAPPSDK-3.0/include/CL/cl.h:1359:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^~~~~~~~~~~~~~~~~~~~
[ 86%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/jconf.cpp.o
[ 89%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/minethd.cpp.o
make[2]: *** No rule to make target '/home/alvin/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'bin/libxmrstak_opencl_backend.so'.  Stop.
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/xmrstak_opencl_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_opencl_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

Here's the error I'm getting. Any ideas?

**Comment by psychocrypt** [comment]
Your OpenCl libraries was not found. Could you please run all command
including cmake in an emty folder and post the output.
If the compile crash please run `cmake -LA .`

**Comment by jmichaelbarker** [comment]
I also receive the error `No rule to make target '/home/michael/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'bin/libxmrstak_opencl_backend.so'.  Stop.` even after running `sudo ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so /usr/lib/libOpenCL.so.1`. Is there anything else I can attempt?

**Comment by royklopper** [comment]
@jmichaelbarker run `ldconfig` after you linked the library, it should work.

**Comment by jmichaelbarker** [comment]
@royklopper yup, that got it working, thanks!
