### ISSUE TITLE
Trying to build on windows w/ cuda 9.0 & latest VisualStudio

### ISSUE THREAD

**Issue by LegolasGChief** [fireice-uk/xmr-stak#534]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - i5 6600k
  - RX 580 but just trying to build for others

# Compile issues
  - WIN10 64 

Visual Studio Community 2017
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community

https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md#compile

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..

c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error:  --
unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported! [C:\Users\Mike\
source\build\xmrstak_cuda_backend.vcxproj]

# Issue with the execution
  - Do you compile the miner on your own?
  Yes

**Comment by psychocrypt** [comment]
which visual studio version do you use?

**Comment by LegolasGChief** [comment]
Visual Studio Community 2017
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community

**Comment by psychocrypt** [comment]
The file in the error is a file from nvidia. This file guarded that you are
using a to old or to new version of visual studio.
You can remove the guard in this file (but if you get errors after that I
can not help) or downgrade somehow visual studio. Or install cuda 8 and
compile with v140.

**Comment by JerichoJones** [comment]
NVIDIA [Issue](https://devtalk.nvidia.com/default/topic/1022648/cuda-setup-and-installation/cuda-9-unsupported-visual-studio-version-error/)

**Comment by psychocrypt** [comment]
fixed it in #549

**Comment by pe4enko** [comment]
I have the same issue on 606edc9 sha commit.
```
                                                                                                                                                                          
"C:\xmr-stak\build\install.vcxproj" (целевой объект по умолчанию) (1) ->                                                                                                  
"C:\xmr-stak\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3) ->                                                                                                
"C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj" (целевой объект по умолчанию) (7) ->                                                                                     
(CustomBuild конечный объект) ->                                                                                                                                          
  c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/host_config.h(135): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Onl 
y the versions 2012, 2013, 2015 and 2017 are supported! [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]                                                                  
                                                                                                                                                                          
    Предупреждений: 41                                                                                                                                                    
    Ошибок: 1                                                                                                                                                             
```

**Comment by cmorsucci** [comment]
Same issue also on the dev branch

**Comment by iformas** [comment]
Same issue un release 2.2.0
