### ISSUE TITLE
Old Video-Card question.

### ISSUE THREAD

**Issue by bryamamigo** [fireice-uk/xmr-stak#1174]
# Basic information
  - NVIDIA 9500GT

Is there any way to make this old video card work ?, uses Cuda v6.5 I know it is very old but I have many of them. if there is any way to do it, could you tell me how to "build it"? thanks,  have a nice day.

**Comment by kneespan** [comment]
Maybe you can get it working with OpenCL. Check [this](https://github.com/fireice-uk/xmr-stak/pull/1112).

**Comment by bryamamigo** [comment]
Hi thanks for this i want to try it but i question. I need to build the xmr-stak with the amd drivers to use this Solution?

**Comment by TheBulitt** [comment]
Ive tried with a 1GB GTS 250 and it just doesnt work, needs OpenCL 1.2 or Cuda 2.0 I believe. Neither of those requirements are met (OpenCL 1.1 and Cuda 1.1)

**Comment by kneespan** [comment]
I have it working with a GTX 580 3GB - should be OpenCL 1.1 too, no?

**Comment by kneespan** [comment]
@bryamamigo Yes, build with AMD SDK for OpenCL Support. Please see my comment [here](https://github.com/fireice-uk/xmr-stak-amd/issues/97#issuecomment-374763319) for hints for potential problems.

**Comment by bryamamigo** [comment]
i got it but i have 3 problems.

1. I made to compile it, only got 1 error :. `C1189: #error: You are trying to do a 32-bit build. This will all end in tears. I know it. [C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmr-stak-backend.vcxproj`

2. realize i need to compile it in 64 bits. but i got this error: 

`"C: \ xmr-stak-dep \ xmr-stak-master \ build \ install.vcxproj "(default destination) (1) ->
"C: \ xmr-stak-dep \ xmr-stak-master \ build \ ALL_BUILD.vcxproj" (default destination) (3) ->
"C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmr-stak.vcxproj" (default destination) (4) ->
(ClCompile destination) ->
  C: \ xmr-stak-dep \ xmr-stak-master \ xmrstak \ cli \ cli-miner.cpp (628): error C3861: 'IsWindows10OrNewer': the
identifier [C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmr-stak.vcxproj]
  C: \ xmr-stak-dep \ xmr-stak-master \ xmrstak \ cli \ cli-miner.cpp (631): error C3861: 'RequestElevation': the id was not found
entifier [C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmr-stak.vcxproj]`


`"C: \ xmr-stak-dep \ xmr-stak-master \ build \ install.vcxproj" (default destination) (1) ->
"C: \ xmr-stak-dep \ xmr-stak-master \ build \ ALL_BUILD.vcxproj" (default destination) (3) ->
"C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmrstak_opencl_backend.vcxproj" (default destination) (7)
->
 C: \ xmr-stak-dep \ xmr-stak-master \ xmrstak \ backend \ amd \ minethd.cpp (100): error C2039:
'memChunk': not a member of 'xmrstak :: amd :: jconf :: thd_cfg '[C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmrstak_opencl_backend.vcxproj]
  C: \ xmr-stak-dep \ xmr-stak-master \ xmrstak \ backend \ amd \ minethd.cpp (101): error C2039: 'compMode': not a member of 'x
mrstak :: amd :: jconf :: thd_cfg '[C: \ xmr-stak-dep \ xmr-stak-master \ build \ xmrstak_opencl_backend.vcxproj] )`

   ` 40 Warning (s)
    4 Errors`

3.in none of the 2 creates the "xmr-stak.exe"
i tried to build the normal xmr-stak with the -DCUDA_ENABLE = OFF to test if im doing wrong the steps to build it. but no, it compile good, those errors apparears after i edit the files with the new one's from the link. idk if im doing something wrong with the visual studio: / Sorry if those are stupid errors but im new to this and i got poor knowledge about it

**Comment by JerichoJones** [comment]
This card is not supported.  
  
{Legacy List](http://www.nvidia.com/object/IO_32667.html)

**Comment by JayWalker512** [comment]
Nvidia + OpenCL used to work fine in Ubuntu (in version 2.2 of xmr-stak), but it seems to have broken in version 2.3 which is very disappointing. I use this setup because it's much faster/easier to get working in Ubuntu than CUDA. See my instructions here: http://www.brandonfoltz.com/2017/12/mining-monero-on-geforce-210-an-exercise-in-futility/

I've been running it on a GTX 560 and GTX 760 which are supported cards, but the problem just seems to be with configuring them. I'll open an issue specifically about this.

**Comment by psychocrypt** [comment]
please open an new issue and fill out the issue template. Do not foget the
logs
